authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='main'),
    path('contacts/', contats_view),
    path('catalog_apple/', catalog_apple),
    path('iphone_x/', iphone_x),
    path('auth/', include('authapp.urls', 'auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст', default=16)

mainapp/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32, unique=True, verbose_name='Название Категории')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=32, unique=True, verbose_name='Название продукта')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Название Категории')
    short_desc = models.CharField(max_length=64, blank=True, verbose_name='Краткое описание')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.PositiveIntegerField(verbose_name='Цена')
    img_1 = models.ImageField(upload_to='products', null=True, default=None, verbose_name='Фотография')
    img_2 = models.ImageField(upload_to='products', null=True, default=None, verbose_name='Фотография только перед')
    img_3 = models.ImageField(upload_to='products', null=True, default=None, verbose_name='Фотография только зад')
    marketing = models.IntegerField(default=0, null=True,
                                    verbose_name='0=Без маркетинга, 1=Новинки, 2=Популярные, 3=Распродажа')

    def __str__(self):
        return '{}-{}'.format(self.name, self.category)

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email',
                  'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()  # Спрятать поле с паролем

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password', 'email',
                  'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()  # Спрятать поле с паролем

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")
        return data

authapp/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import *
from django.contrib import auth
from django.urls import reverse


# Create your views here.

def login(request):
    title = 'вход'
    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))

        else:
            register_form = ShopUserRegisterForm()
            content = {'title': title, 'register_form': register_form}
            return render(request, 'authapp/register.html', content)

    else:
        register_form = ShopUserRegisterForm()
        content = {'title': title, 'register_form': register_form}
        return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'редактирование'
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES,
                                     instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
        return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        content = {'title': title, 'edit_form': edit_form}
        return render(request, 'authapp/edit.html', content)

mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import *


# Create your views here.
def index_view(request):
    products = Product.objects.all()
    marketing_new = Product.objects.filter(marketing__startswith=1)
    marketing_popular = Product.objects.filter(marketing__startswith=2)
    # marketing_sale = Product.objects.filter(marketing_startswith=3)

    content = {
        'products': products,
        'marketingNew': marketing_new,
        'marketingPopular': marketing_popular,
        # 'marketingSale': marketing_sale
    }
    return render(request, 'mainapp/index.html', content)


def contats_view(request):
    return render(request, 'mainapp/contact.html')


def catalog_apple(request):
    products_apple = Product.objects.filter(category__pk=1)

    content = {
        'products_apple': products_apple
    }
    return render(request, 'mainapp/catalog/apple.html', content)


def iphone_x(request):
    charectiristic_1 = [{'Тип:': 'смартфон', 'Версия ОС:': 'iOS 11', 'Тип корпуса:': 'классический',
                         'Материал корпуса:': 'стекло', 'Конструкция:': 'водозащита', 'тип SIM:': 'nano SIM',
                         'Количество SIM:': '1', 'Вес:': '174г', 'Размеры (ШхВхТ):': '70,9х143,6х7,7мм',
                         'Тип экрана:': 'цветной OLED, сенсорный'}]

    charectiristic_2 = [{'Тип сенсорного экрана:': 'сультитач, емкостный', 'Диагональ:': '5.8 дюймов',
                         'Сила нажатия на экран:': 'есть', 'Размер изображения:': '2436х1125',
                         'Число пикселей на дюйм:': '463', 'Соотношение сторон:': '19,5:9',
                         'Автоматический поворот экрана:': 'есть', 'Тыловая камера:': 'двойная 12/12 МП',
                         'Фотовспышка:': 'тыльная, светодиодная'}]
    return render(request, 'mainapp/catalog/Apple/iphone_x.html',
                  {'charectiristic_1': charectiristic_1, 'charectiristic_2': charectiristic_2})


# def products(r)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
		{{ title|title }}
		{% endblock %}
	</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
	<link href="{% static 'style/main.css' %}" rel="stylesheet">
	{% block js %}
	{% endblock %}
</head>

<body>
	<div class="container">
		<div class="login">
			<div class="h2 text-center head">
			Вход в систему
			</div>
		{% block content %}
		{% endblock %}
		</div>
	</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
	<form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ edit_form.as_p }}
		<input class="form-control" type="submit" value="сохранить">
	</form>
		<button class="btn btn-round form-control last">
				<a href="{% url 'main' %}" class="">
				на главную
				</a>
		</button>
	<div class="user_avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
	<form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
		{% csrf_token %}
		{{ login_form.as_p }}
		<br>
		<input class="form-control" type="submit" value="войти">
	</form>
	<button class="btn btn-round form-control">
		<a href="{% url 'auth:register' %}" class="">
			зарегистрироваться
		</a>
	</button>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
	<form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ register_form.as_p }}
		<br>
		<input class="form-control" type="submit" value="зарегистрироваться">
	</form>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="ru">

<head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
	<link href="{% static 'style/main.css' %}" rel="stylesheet">
	<title>
		{% block title %}
		{% endblock %}
	</title>
	
</head>
<body>



	<header>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark">
			<img class="navbar-brand img-fluid rounded-circle" src="{% static 'img/Logo.jpg' %}" alt="Xpamou" width="100" height="100">
			  	<div class="navbar-collapse">
			    	<ul class="navbar-nav main_nav">
			    		{% block nav_main %}
							<li class="nav-item">
						{% endblock %}
							<a class="nav-link" href="/">Главная</a>
							</li>
							<li class="dropdown">
						{% block nav_product %}
						    <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">
						      Каталог 
						{% endblock %}
						      <b class="caret"></b>
						    </a>
						    <ul class="dropdown-menu">
						      <li><a href="/catalog_apple/">Apple</a></li>
						      <li><a href="#">Sumsung</a></li>
						      <li><a href="#">OnePlus</a></li>
						    </ul>
							</li>
						{% block nav_contact %}
						    <li class="nav-item">
						{% endblock %}
						    	<a class="nav-link" href="/contacts/">Контакты</a>
						    </li>
			    	</ul>
			  	</div>
			  	{% block time%}
				  	{% if user.is_authenticated %}
					<li>
						<a href="{% url 'auth:edit' %}">
						{{ user.first_name|default:'Пользователь' }}
						</a>
					</li>
						{% endif %}
					<li>
						{% if user.is_authenticated %}
							<a href="{% url 'auth:logout' %}">выйти</a>
						{% else %}
							<a href="{% url 'auth:login' %}">войти</a>
						{% endif %}
					</li>
			  	{% endblock %}
		</nav>
		
	</header>


	{% block main %}
	{% endblock %}

	{% block main_2 %}
	{% endblock %}

	<footer class="footer bg-dark foot">
	        <div class="row">
	            <div class="col-md-5 p-4">
	                <h5 class="orange">Xpamou</h5>
	                <div class="row">
                        <ul class="list">
                            <li><a href="">Лицензия</a></li>
                            <li><a href="">Поддержка</a></li>
                            <li><a href="">О нас</a></li>
	                </div>
	                <ul class="nav">
	                    <li class="nav-item"><a href="" class="nav-link"><i class="fa fa-facebook fa-lg"></i></a></li>
	                    <li class="nav-item"><a href="" class="nav-link"><i class="fa fa-twitter fa-lg"></i></a></li>
	                    <li class="nav-item"><a href="" class="nav-link"><i class="fa fa-github fa-lg"></i></a></li>
	                    <li class="nav-item"><a href="" class="nav-link"><i class="fa fa-instagram fa-lg"></i></a></li>
	                </ul>
	                <br>
	            </div>
	            <div class="col-md-2">
	                <h5 class="text-md-right orange">Подписка на новости</h5>
	                <hr>
	            </div>
	            <div class="col-md-3">
	                <form>
	                    <fieldset class="form-group">
	                        <input type="email" class="form-control" id="InputEmail1" placeholder="Введите почту">
	                    </fieldset>
	                    <fieldset class="form-group text-xs-right">
	                        <button type="button" class="btn btn-secondary-outline btn-lg">Отправить</button>
	                    </fieldset>
	                </form>
	            </div>
	        </div>
	</footer>

	{% block script %}
	{% endblock %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</body>
</html>

mainapp/templates/mainapp/catalog/Apple/iphone_x.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}

{% block titel %}
	Iphone
{% endblock %}


	{% block main %}
	 	<div class="row w-100 p-4">
			<div class="col-md-3">
				<img class="img-fluid" src="{% static 'img/iphone-x-64_1.jpg' %}">
			</div>

			<div class="col-md-3">
				<table class="table table_set">
				  <tbody>
				  	{% for i in charectiristic_1 %}
						{% for value, key in i.items%}
							<tr>
						      <th scope="row">{{value}}</th>
						      <td>{{key}}</td>
						    </tr>
				    	{% endfor %}
					{% endfor %}
				  </tbody>
				</table>
			</div>

			<div class="col-md-3">
				<img class="img-fluid" src="{% static 'img/iphone-x-64_2.jpg' %}">
			</div>

			<div class="col-md-3">
				<table class="table table_set">
				  <tbody>
				  	{% for i in charectiristic_2 %}
						{% for value, key in i.items%}
							<tr>
						      <th scope="row">{{value}}</th>
						      <td>{{key}}</td>
						    </tr>
				    	{% endfor %}
					{% endfor %}
				  </tbody>
				</table>
				<div class="dropdown">
					  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					    Купить
					  </button>
					  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					    <a class="dropdown-item" href="#">64Гб</a>
					    <a class="dropdown-item" href="#">128Гб</a>
					    <a class="dropdown-item" href="#">256Гб</a>
					  </div>
					</div>
			</div>
		</div>
	
	{% endblock %}

	{% block script %}
	<script type="text/javascript" src="https://unpkg.com/popper.js"></script>
	{% endblock %}

mainapp/templates/mainapp/catalog/apple.html
{% extends "mainapp/catalog/base_category.html" %}
{% load staticfiles %}

{% block titel %}
	Apple
{% endblock %}


{% block nav_product %}
	    <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle active">
	    	Apple
	{% endblock %}      

	{% block main %}
		<div class="marketing">
	      <div class="row">
	      	{% for prod in products_apple %}
	        <div class="col-lg-4 ">
	        	<div class ="container_cover">
	            	<img class="img-fluid" src="{{prod.img_2.url}}" alt="{{prod.name}}" width="340" height="340">
		            <a href="#" class="overlay">
						<div class="text_cover">
							<h3>Описание</h3>
							<p>{{prod.description}}
							</p>
						</div>
					</a>
				</div>
	            <h2>{{product.name}}</h2>
	            <p>{{prod.short_desc}}</p>
	            <p class="price">Цена: {{prod.price}} рублей</p>
	            <p><a class="btn btn-secondary" href="#" role="button">В корзину &nbsp;<i class="fa fa-shopping-basket" aria-hidden="true"></i></a></p>
	        </div>
	        {% endfor %}
	      </div>
	    </div>
	 {% endblock %}

mainapp/templates/mainapp/catalog/base_category.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}

{% block titel %}
{% endblock %}


	{% block nav_product %}
	    <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle active">
	{% endblock %}   

	{% block main %}
		<div class="marketing">
	      <div class="row">
	        <div class="col-lg-4 ">
	        	<div class ="container_cover">
	            	<img class="img-fluid" src="{% static 'img/ipad_mini_blue_1.jpg' %}" alt="OnePlus 3t" width="340" height="340">
		            <a href="#" class="overlay">
						<div class="text_cover">
							<h3>Описание</h3>
							<p>Планшет 7.85", 2048x1536, TFT IPS Встроенная память 128 Гб, без слота для карт памяти IOS, ОЗУ 2 Гб,
							процессор Apple A8 Wi-Fi, Bluetooth, NFC
							</p>
						</div>
					</a>
				</div>
	            <h2>Ipad mini</h2>
	            <p>Создан для настояших ценителей.</p>
	            <p class="price">Цена: 1700 рублей</p>
	            <p><a class="btn btn-secondary " href="#" role="button">В корзину &nbsp;<i class="fa fa-shopping-basket" aria-hidden="true"></i></a></p>
	        </div>
	        <div class="col-lg-4">
	        	<div class ="container_cover">
	            	<img class="img-fluid" src="{% static 'img/iphone-8_1.jpg' %}" alt="ipad pro" width="340" height="340">
	            	<a href="#" class="overlay">
						<div class="text_cover">
							<h3>Описание</h3>
							<p>смартфон, iOS 11 экран 4.7", разрешение 1334x750 камера 12 МП, автофокус, F/1.8 память 256 Гб,
							 без слота для карт памяти 3G, 4G LTE, LTE-A, Wi-Fi, Bluetooth, NFC, GPS, ГЛОНАСС вес 148 г, ШxВxТ 67.30x138.40x7.30 мм
							</p>
						</div>
					</a>
				</div>
	            <h2>Iphone 8</h2>
	            <p>Создан профессионалами для профессионалов <br> </p>
	            <p class="price">Цена: 1700 рублей</p>
	            <p><a class="btn btn-secondary" href="#" role="button">В корзину &nbsp;<i class="fa fa-shopping-basket" aria-hidden="true"></i></a></p>
	        </div>
	        <div class="col-lg-4 ">
	        	<div class ="container_cover">
	            	<img class="img-fluid" src="{% static 'img/iphone-x-64_1.jpg' %}" alt="iphone x" width="340" height="340">
	            	<a href="/iphone_x/" class="overlay">
						<div class="text_cover">
							<h3>Описание</h3>
							<p>Экран 5.8" 2436x1125 Стандарт связи	3G, GSM, LTE Тип корпуса классический Размеры (ВxШxТ) 143.6x70.9x7.7 мм Вес 174 г
							 Встроенная память 64 ГБ Встроенный GPS	есть Процессор Apple A11 Bionic 
							</p>
						</div>
					</a>
				</div>
	            <h2>Iphone X</h2>
	            <p>Долгожданная новинка этого года</p>
	            <p class="price">Цена: 1700 рублей</p>
	            <p><a class="btn btn-secondary" href="#" role="button">В корзину &nbsp;<i class="fa fa-shopping-basket" aria-hidden="true"></i></a></p>
	        </div>
	      </div>
	    </div>
	 {% endblock %}

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}

{% block titel %}
	Главная
{% endblock %}

	
	{% block time%}
		{% if user.is_authenticated %}
			<li>
				<a href="{% url 'auth:edit' %}">
				{{ user.first_name|default:'Пользователь' }}
				</a>
			</li>
				{% endif %}
			<li class="pl-4">
				{% if user.is_authenticated %}
					<a href="{% url 'auth:logout' %}">выйти</a>
				{% else %}
					<a href="{% url 'auth:login' %}">войти</a>
				{% endif %}
			</li>
	{% endblock %}


	
	{% block nav_main %}
		<li class="nav-item active">
	{% endblock %}

	{% block main %}
	<video id="video_bg" autoplay="autoplay" loop="loop">
		<source src="{% static 'video/rain.mp4' %}" type="video/mp4"></source>
		<source src="{% static 'video/rain.webm' %}" type="video/webm"></source>
	</video>
		<div id="carouselExampleIndicators" class="carousel slide carousel_size" data-ride="carousel">
		  	<ol class="carousel-indicators">
			    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		 	</ol>
			<div class="carousel-inner">
			    <div class="carousel-item active">
			    	<img class="d-block h-50 w-100" src="{% static 'img/Auto_foto.jpg' %}" alt="Первый слайд">
			    		<div class="carousel-caption d-none d-md-block">
						    <h3>Акции</h3>
						    <p>До 70% скидки о них вы можете узнать по телефону</p>
					    </div>
			    </div>
			    <div class="carousel-item">
			     	<img class="d-block h-50 w-100" src="{% static 'img/auto_foto_2.jpg' %}" alt="Второй слайд">
			     		<div class="carousel-caption d-none d-md-block auto_text_2">
						    <h3>Более 1000 моделей</h3>
						    <p>Представлены все производители</p>
					    </div>
			    </div>
			    <div class="carousel-item">
			        <img class="d-block h-50 w-100" src="{% static 'img/auto_foto_3_1.jpg' %}" alt="Третий слайд">
				        <div class="carousel-caption d-none d-md-block">
						    <h3>Наш магазин работает с 1976 года</h3>
						    <p>Открыто более 90 магазинов в РФ и более 20 в Европе</p>
					    </div>
			    </div>
			</div>
		    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
		    	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    	<span class="sr-only">Previous</span>
		    </a>
		    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		    	<span class="carousel-control-next-icon" aria-hidden="true"></span>
		    	<span class="sr-only">Next</span>
		    </a>
		</div>



		<div class="container pt-4">
			<ul class="nav nav-tabs" role="tablist">
			    <li class="nav-item">
			  	  <a class="nav-link active tab_set" href="#new"  data-toggle="tab">Новинки</a>
			    </li>
			    <li class="nav-item">
			    	<a class="nav-link tab_set" href="#popular" data-toggle="tab">Популярные</a>
			    </li>
			    <li class="nav-item">
			    	<a class="nav-link tab_set" href="#sale"  data-toggle="tab">Распродажа</a>
			    </li>
			</ul>
		</div>


			<div class="tab-content ">
			    <div class="tab-pane active" id="new">
		  			<div class="marketing">
				      <div class="row">
				      	{% for marketings in marketingNew %}
					        <div class="col-xs-12 col-sm-6 col-lg-4">
						        <a href="#">
						            <img class="img-fluid rounded-circle" src="{{marketings.img_1.url}}" alt="{{marketings.name}}" width="340" height="340">
						        </a>
					            <h2>{{marketings.name}}</h2>
					            <p>{{marketings.short_desc}}</p>
					            <p><a class="btn btn-secondary" href="#" role="button">Детали &raquo;</a></p>
					        </div>
				        {% endfor %}
				      </div>
				    </div>
			    </div>

			    <div class="tab-pane" id="popular">
				    <div class="marketing">
				      <div class="row">
				        {% for marketingsPopular in marketingPopular %}
					        <div class="col-xs-12 col-sm-6 col-lg-4">
						        <a href="#">
						            <img class="img-fluid rounded-circle" src="{{marketingsPopular.img_1.url}}" alt="{{marketingsPopular.name}}" width="340" height="340">
						        </a>
					            <h2>{{marketingsPopular.name}}</h2>
					            <p>{{marketingsPopular.short_desc}}</p>
					            <p><a class="btn btn-secondary" href="#" role="button">Детали &raquo;</a></p>
					        </div>
				        {% endfor %}
				      </div>
				    </div>			
				</div>

<!-- 			    <div class="tab-pane" id="sale">
			  	<div class="marketing">
				      <div class="row">
				        {% for marketingsSale in marketingSale %}
					        <div class="col-xs-12 col-sm-6 col-lg-4">
						        <a href="#">
						            <img class="img-fluid rounded-circle" src="{{marketingsSale_1.img.url}}" alt="{{marketingsSale.name}}" width="340" height="340">
						        </a>
					            <h2>{{marketingsSale.name}}</h2>
					            <p>{{marketingsSale.desc}}</p>
					            <p><a class="btn btn-secondary" href="#" role="button">Детали &raquo;</a></p>
					        </div>
				        {% endfor %}
				      </div>
				    </div>
			    </div> -->
			</div>
	{% endblock %}


			